### ISSUE TITLE
Update pavement.py for Py3.

### ISSUE THREAD

**Issue by adiroiban** [chevah/pythia#22]
The current pavememnt.py from pythia is py2 only syntax.

it should be updated to py3.

one option is to use - https://github.com/asottile/pyupgrade for automat migration.

compileall can be removed, as that  was a hack for py2 to allow unicode handling...but py3 should work just fine.

I will ask Dan to  work on this... trying to see how to assign this ticket to Dan.

**Comment by dumol** [comment]
@danuker, fixed in #25?

**Comment by adiroiban** [comment]
Yes. I think that this can be closed. Thanks!
