### ISSUE TITLE
Stop building stuff, starting with cryptography.

### ISSUE THREAD

**Issue by dumol** [chevah/pythia#35]
The way we build Python, every major version upgrade is a massive pain in the rear, because I have to forward-port the `libedit` patches. And then fix any new issues with our builds.

Only minor version updates are (quickly) doable, but these are limited by what upstream does. In the case of Python 3.8, upstream stopped providing embeddable Windows packages at version 3.8.10. Compare https://www.python.org/downloads/release/python-3810/ with https://www.python.org/downloads/release/python-3811/.

[…]

Given the Rust dependency of `cryptography`, I think the way forward would be to stop trying to build it ourselves. Just use the upstream wheels with embedded OpenSSL.

Ideally, also use upstream Python packages on all OS'es, just like on Windows. Effectively, this means not building anything at all, just like we already do on Windows for this repo. Given the way Python is packaged upstream, this would mean being ready to jump to the latest major Python version rather early. E.g. for the 3.8.x lifecycle, be on Python 3.9.x before Python 3.8.11 was released.

_Originally posted by @dumol in https://github.com/chevah/pythia/issues/34#issuecomment-1153574889_

**Comment by adiroiban** [comment]
I think that we can remove libedit.

For Python, there is no need to use 3.8
We can go with 3.10 or whatever is the latest version.

----------

> Given the Rust dependency of cryptography, I think the way forward would be to stop trying to build it ourselves. Just use the upstream wheels with embedded OpenSSL.

yes. and only have a single Linux download archive.

-------

**Comment by dumol** [comment]
Partially fixed through https://github.com/chevah/pythia/pull/38, which switched to using `cryptography` wheels everywhere.

Not building Python is not an option on Linux. Given that building it on macOS is very similar to building on Linux, it's not worth the trouble to stop building Python on macOS.
