### ISSUE TITLE
Pythia support for mac M1 chip

### ISSUE THREAD

**Issue by adiroiban** [chevah/pythia#37]
I hope that the porting is not a big deal as in the end, this is ARM64

I see some info here https://github.com/pyca/cryptography/issues/6161

Mișu, give it a try on scaleway and see if we can build the python package.

This is low priority, but if the m1 chips have great computing power, maybe we will see them more often on servers.

The mac studio and mac pro hardware are a joke in terms of servers...so I don't have high hopes from apple producing a good server platform.

Thanks

**Comment by dumol** [comment]
Fixed through https://github.com/chevah/pythia/pull/39.
