### ISSUE TITLE
Try getting a musl wheel for `psutil`.

### ISSUE THREAD

**Issue by dumol** [chevah/pythia#60]
> Unfortunately, there is no musl wheel for psutil.

Maybe just add a comment to inform why we have `psutil`.

In the future updates, we can review the pypi files for psutil.. maybe musl will be added in the future and we can remove this.

I see that nobody asked for `musl`  package https://github.com/giampaolo/psutil/issues?q=is%3Aissue+is%3Aopen+musl

Maybe we can create a PR and add support for musl

It should be possible to build it via Docker

_Originally posted by @adiroiban in https://github.com/chevah/pythia/issues/59#issuecomment-2154831351_

**Comment by adiroiban** [comment]
I think that the best way forward is to send a pull request upstream that implementes generating the musl wheels.
