### ISSUE TITLE
Self-hosted runners

### ISSUE THREAD

**Issue by dumol** [chevah/pythia#8]
We need to support pythia on all the SFTPPlus v4 OSes.

My suggest is to keep the repo public but add private runners .... we will see if people will be tempted to create PR with malicious code... as a first steps, GitHub Actions can be configured to run actions for this repo only from GitHub and Chevah own org.

_Originally posted by @adiroiban in https://github.com/chevah/pythia/issues/5#issuecomment-727624935_

**Comment by dumol** [comment]
Relevant: https://docs.github.com/en/free-pro-team@latest/actions/hosting-your-own-runners/about-self-hosted-runners#supported-operating-systems-for-self-hosted-runners

Notably missing:

  * RHEL/CentOS 8
  * Amazon Linux 2
  * CentOS 5 (for the generic x64 Linux build)
  * Alpine Linux.

Note that Ubuntu 16.04 on ARM64 (for the generic arm64 Linux build) should work, according to https://github.blog/changelog/2019-12-03-github-actions-self-hosted-runners-on-arm-architectures/.

**Comment by adiroiban** [comment]
I expect Centos8 and AMZ 2 will work as they are "modern" version on which .net core can run.

So for now, only add private self-hosted runners for Centos and AMZ2
