### ISSUE TITLE
Package publication

### ISSUE THREAD

**Issue by dumol** [chevah/pythia#9]
We need to find a way to publish them to http://binary.chevah.com/testing

_Originally posted by @adiroiban in https://github.com/chevah/pythia/issues/5#issuecomment-727624935_

**Comment by adiroiban** [comment]
My suggestion is to use a simple HTTP PUT or SFTP client to push the files from GitHub Actions infra

On our Binary site, we can install SFTPPlus server which an account that is restricted to only upload (add new files).
That account can't delete and can't overwrite.
